(require 'owdriver)
(require 'el-expectations)

(expectations
  (desc "define-command not add keymap")
  (expect nil
    (let ((called-add-keymap))
      (stub owdriver-add-keymap => (setq called-add-keymap t))
      (owdriver-define-command next-line nil)
      called-add-keymap))
  (desc "define-command define command")
  (expect t
    (commandp 'owdriver-do-next-line))
  (desc "define-command check function")
  (expect (mock (call-interactively 'next-line))
    (owdriver-do-next-line))
  (desc "define-command add keymap")
  (expect t
    (let ((called-add-keymap))
      (stub owdriver-add-keymap => (setq called-add-keymap t))
      (owdriver-define-command next-line t)
      called-add-keymap))
  (desc "define-command add keymap with arg")
  (expect (mock (owdriver-add-keymap (key-description (nth 0 (where-is-internal 'isearch-forward global-map)))
                                     'owdriver-do-isearch-forward))
    (owdriver-define-command isearch-forward t))
  (desc "define-command have body")
  (expect '(forward-char)
    (let ((called))
      (stub next-line => (push 'next-line called))
      (stub forward-char => (push 'forward-char called))
      (owdriver-define-command next-line t (forward-char))
      (owdriver-do-next-line)
      called))
  )

